pipeline{
    
agent any

parameters{
    string(name: 'profession', defaultValue: '',description: 'What is your current profession?')
    string(name: 'BIOGRAPHY', defaultValue: '',description: 'Enter your biography?')
}
stages{
stage ('First phase'){
steps{
echo 'Hi. This is Kalpesh'
}
}
stage ('second phase'){
    when{
        branch 'production'
    }
steps{
echo 'Deploying'
}
}
stage ('third phase'){
steps {
echo "Hello ${params.profession}"
echo "Biography ${params.BIOGRAPHY}"
}
}
stage ('fourth phase'){
    options{
        timeout(time: 1,unit: 'HOURS')
    }
    steps{
        echo 'Hello World'
    }
}
}
}
